- hosts: localhost
  tasks:
    - name: Create service
      command: kubectl apply -f create-fastapi-service.yml
    
    - name: Create Auto Scaling
      command: kubectl autoscale deployment fastapi-api --cpu-percent=50 --min=1 --max=10

    - name: Install Metrics Server
      command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml